name: Docs Dev Publish
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    if: github.repository_owner == 'Qiskit'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U virtualenv setuptools wheel tox
        sudo apt-get install graphviz pandoc
    - name: Build docs dev
      run: RUSTWORKX_DEV_DOCS=1 tox -edocs
    - name: Bypass Jekyll Processing # Necessary for setting the correct css path
      run: touch docs/build/html/.nojekyll
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs/build/html/
        target-folder: dev/
